let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Office Chair",
    price: 150,
    desc: "A comfortable, ergonomic chair for getting your office work done.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Office Desk",
    price: 350,
    desc: "A table perfect for performing one's writing or typing work.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Sectional Couch",
    price: 650,
    desc: "A nice sectional couch for resting or laying down on.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Coffee Table",
    price: 100,
    desc: "A low table designed to be placed in a sitting area for convenient support of small items.",
    img: "images/img-4.jpg",
  },
  {
    id: "jfhgbvnabc",
    name: "Floor Lamp",
    price: 75,
    desc: "A tall lamp designed to stand on the floor.",
    img: "images/img-5.jpg",
  },
  {
    id: "ioytrhndef",
    name: "Recliner",
    price: 400,
    desc: "An upholstered armchair that can be tilted backward.",
    img: "images/img-6.jpg",
  },
  {
    id: "wuefbncxghi",
    name: "Stool",
    price: 55,
    desc: "A seat great for sitting at the counter.",
    img: "images/img-7.jpg",
  },
  {
    id: "thyfhcjkl",
    name: "Futon",
    price: 300,
    desc: "A low sofa that can be used as a bed.",
    img: "images/img-8.jpg",
  },
  {
    id: "jfhgbvncba",
    name: "Dining Table Set",
    price: 1250,
    desc: "A dining table with 6 chairs.",
    img: "images/img-9.jpg",
  },
  {
    id: "ioytrhnfed",
    name: "Persion Rug",
    price: 250,
    desc: "A nice imported living room Persian rug.",
    img: "images/img-10.jpg",
  },
  {
    id: "wuefbncxihg",
    name: "Oak Dresser",
    price: 550,
    desc: "A multi drawer dresser made from the finest oak.",
    img: "images/img-11.jpg",
  },
  {
    id: "thyfhclkj",
    name: "Standing Mirror",
    price: 250,
    desc: "A standing mirror for full body reflection.",
    img: "images/img-12.jpg",
  },
];
