let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Office Chair",
    price: 150,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Office Desk",
    price: 200,
    desc: "A table perfect for performing one's writing or typing work.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Sectional Couch",
    price: 400,
    desc: "An upholstered furniture that consists of two or more joined sections for sitting.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Coffee Table",
    price: 100,
    desc: "A low table designed to be placed in a sitting area for convenient support of small items.",
    img: "images/img-4.jpg",
  },
  {
    id: "jfhgbvnabc",
    name: "Floor Lamp",
    price: 50,
    desc: "A tall lamp designed to stand on the floor.",
    img: "images/img-5.jpg",
  },
  {
    id: "ioytrhndef",
    name: "Recliner",
    price: 350,
    desc: "An upholstered armchair that can be tilted backward.",
    img: "images/img-6.jpg",
  },
  {
    id: "wuefbncxghi",
    name: "Stool",
    price: 40,
    desc: "A seat great for sitting at the counter.",
    img: "images/img-7.jpg",
  },
  {
    id: "thyfhcjkl",
    name: "Futon",
    price: 250,
    desc: "A low sofa that can be used as a bed.",
    img: "images/img-8.jpg",
  },
];
